/**
 * Calendar seeding from `src/data/content-calendar-seed.json`.
 *
 * The new (Phase 2) seed file is generated by
 * `scripts/generate-calendar-seed.mjs` and obeys:
 *
 *   - 13 weeks, ~10–12 items per week
 *   - Per item: id, week (1-13), day, series, template, format,
 *     pillar, grid_color_profile, grid_position {row,col}, content_data,
 *     caption, ai_rationale, status
 *   - All series and ~all templates from the current library are exercised
 *
 * This loader maps each seed entry to a CalendarItem the runtime store can
 * persist, anchoring week 1 to the next upcoming Monday so the dashboard
 * lights up immediately.
 *
 * Note: `grid_color_profile` is intentionally NOT persisted on the
 * CalendarItem — the live grid derives the color from the template
 * definition at render time. The seed carries it only for verification
 * during generation.
 */

import calendarSeed from "@/data/content-calendar-seed.json";
import { getSeriesBySlug } from "@/lib/db/data-loader";
import type {
  CalendarItem,
  CalendarStatus,
  ContentData,
  ContentFormat,
  GridPosition,
  PillarSlug,
} from "@/lib/types";

interface SeedEntry {
  id?: string;
  week: number;
  day: string;
  series: string;
  template: string;
  format: string;
  pillar?: string;
  grid_color_profile?: string | null;
  grid_position?: { row: number; col: number } | null;
  content_data: Record<string, unknown>;
  caption: string | null;
  ai_rationale: string | null;
  status?: string;
}

interface SeedJson {
  metadata: Record<string, unknown>;
  content: SeedEntry[];
}

const DAY_OFFSETS: Record<string, number> = {
  monday: 0,
  tuesday: 1,
  wednesday: 2,
  thursday: 3,
  friday: 4,
  saturday: 5,
  sunday: 6,
};

const VALID_FORMATS = new Set<ContentFormat>(["story", "post", "reel"]);
const VALID_PILLARS: ReadonlySet<PillarSlug> = new Set([
  "engage",
  "educate",
  "inspire",
  "connect",
  "convert",
]);
const VALID_STATUSES = new Set<CalendarStatus>([
  "suggested",
  "approved",
  "editing",
  "exported",
  "posted",
]);

function newId(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `cal_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
}

function isoDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

function nextMondayFrom(reference: Date): Date {
  const d = new Date(reference);
  d.setHours(0, 0, 0, 0);
  const day = d.getDay(); // 0=Sun, 1=Mon, ..., 6=Sat
  const offset = day === 1 ? 7 : (8 - day) % 7 || 7;
  d.setDate(d.getDate() + offset);
  return d;
}

function parseHashtags(caption: string | null): string[] {
  if (!caption) return [];
  const matches = caption.match(/#[\w]+/g);
  if (!matches) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const tag of matches) {
    const stripped = tag.slice(1);
    if (!seen.has(stripped)) {
      seen.add(stripped);
      out.push(stripped);
    }
  }
  return out;
}

function normaliseFormat(value: string): ContentFormat {
  // Carousels live on the grid like posts and use the post component
  // path; the runtime store only knows story/post/reel, so collapse here.
  if (value === "carousel") return "post";
  return VALID_FORMATS.has(value as ContentFormat)
    ? (value as ContentFormat)
    : "story";
}

function normalisePillar(
  value: string | undefined,
  fallback: PillarSlug,
): PillarSlug {
  if (value && VALID_PILLARS.has(value as PillarSlug)) {
    return value as PillarSlug;
  }
  return fallback;
}

function normaliseStatus(value: string | undefined): CalendarStatus {
  if (value && VALID_STATUSES.has(value as CalendarStatus)) {
    return value as CalendarStatus;
  }
  return "approved";
}

function normaliseGridPosition(
  raw: SeedEntry["grid_position"],
): GridPosition | null {
  if (!raw) return null;
  return { row: raw.row, column: raw.col };
}

export interface SeedCalendarOptions {
  /** Monday to anchor week 1 of the seed plan to. Defaults to next Monday. */
  startDate?: Date;
}

export interface SeedCalendarResult {
  items: CalendarItem[];
  weekCount: number;
}

export function buildSeedCalendarItems(
  options: SeedCalendarOptions = {},
): SeedCalendarResult {
  const seed = calendarSeed as unknown as SeedJson;
  const startDate = options.startDate ?? nextMondayFrom(new Date());
  const startMs = startDate.getTime();

  const sortCounters = new Map<string, number>();
  const items: CalendarItem[] = [];
  const weeksSeen = new Set<number>();

  for (const entry of seed.content) {
    const dayOffset = DAY_OFFSETS[entry.day.toLowerCase()];
    if (dayOffset === undefined) continue;

    const weekOffsetMs = (entry.week - 1) * 7 * 24 * 60 * 60 * 1000;
    const dayOffsetMs = dayOffset * 24 * 60 * 60 * 1000;
    const itemDate = new Date(startMs + weekOffsetMs + dayOffsetMs);
    const scheduled_date = isoDate(itemDate);

    const sortKey = `${entry.week}:${entry.day}`;
    const sort_order = sortCounters.get(sortKey) ?? 0;
    sortCounters.set(sortKey, sort_order + 1);

    const format = normaliseFormat(entry.format);
    const seriesPillar = (getSeriesBySlug(entry.series)?.pillar ??
      "engage") as PillarSlug;
    const pillar = normalisePillar(entry.pillar, seriesPillar);
    const now = new Date().toISOString();

    weeksSeen.add(entry.week);

    items.push({
      id: entry.id ?? newId(),
      scheduled_date,
      scheduled_time: null,
      week_number: entry.week,
      day_of_week: entry.day.toLowerCase(),
      series_slug: entry.series,
      pillar,
      template_slug: entry.template,
      format,
      status: normaliseStatus(entry.status),
      content_data: (entry.content_data ?? {}) as ContentData,
      caption: entry.caption ?? null,
      hashtags: parseHashtags(entry.caption),
      ai_rationale: entry.ai_rationale ?? null,
      generation_prompt: null,
      grid_position: normaliseGridPosition(entry.grid_position),
      sort_order,
      created_at: now,
      updated_at: now,
    });
  }

  return { items, weekCount: weeksSeen.size };
}
